### ISSUE TITLE
陈老师你好，请问在UnitTest1中的“开始测试getValue(String key)”无论输入什么路径都没反应呢？

### ISSUE THREAD

**Issue by 1392081456** [Jiangyuan-Chen/javaproject#11]

**Comment by Jiangyuan-Chen** [comment]
要求输入路径的时候试试"./"   :)

**Comment by 1392081456** [comment]
![image](https://user-images.githubusercontent.com/56790707/163293055-adc6b52d-cc80-4c9f-91c7-a5abeeff2b23.png)
您看，我的test1.txt在gog(和src在同级目录)和test文件夹中都有，按照您的提示， 我在测试gogo文件夹中输入路径为./gogo/test1.txt ，  在测试test文件夹中用的是./test1.txt，但是都没有响应，还望您看到issue能给予回复，感谢！

**Comment by 1392081456** [comment]
![image](https://user-images.githubusercontent.com/56790707/163302323-471aeb0c-a054-4914-8764-f45735ad2937.png)
陈老师您好，经过debug，有出现这个问题，但是我在cmd中查询对应端口的时候，并没有出现被占用.....有点疑惑....望尽快回复！

**Comment by Jiangyuan-Chen** [comment]
> ![image](https://user-images.githubusercontent.com/56790707/163293055-adc6b52d-cc80-4c9f-91c7-a5abeeff2b23.png)
> 您看，我的test1.txt在gog(和src在同级目录)和test文件夹中都有，按照您的提示， 我在测试gogo文件夹中输入路径为./gogo/test1.txt ， 在测试test文件夹中用的是./test1.txt，但是都没有响应，还望您看到issue能给予回复，感谢！

我的意思是路径直接输入"./"，不要加具体的文件名。这里的测试其实我写得不太好，应该直接系统默认读取工作目录就好了。建议你看一下getFileValue方法的具体实现，应该会对你的理解有帮助。另外为啥你会找到我做的项目而且还要跑一遍，这都是好久之前做的了而且很不完善 = =

**Comment by Jiangyuan-Chen** [comment]
> ![image](https://user-images.githubusercontent.com/56790707/163302323-471aeb0c-a054-4914-8764-f45735ad2937.png)
> 陈老师您好，经过debug，有出现这个问题，但是我在cmd中查询对应端口的时候，并没有出现被占用.....有点疑惑....望尽快回复！

这里我也不太清楚呢，我感觉不是对应端口被占用的原因，因为要是因为被占用的话一开始就不可能连接的上。我估计重新debug一次就没有这种情况了吧。这种情况我也没见过，你可以百度查查原因。

**Comment by 1392081456** [comment]
> 

感谢， 我看了源码，已经解决！

**Comment by 1392081456** [comment]
> > ![image](https://user-images.githubusercontent.com/56790707/163293055-adc6b52d-cc80-4c9f-91c7-a5abeeff2b23.png)
> > 您看，我的test1.txt在gog(和src在同级目录)和test文件夹中都有，按照您的提示， 我在测试gogo文件夹中输入路径为./gogo/test1.txt ， 在测试test文件夹中用的是./test1.txt，但是都没有响应，还望您看到issue能给予回复，感谢！
> 
> 我的意思是路径直接输入"./"，不要加具体的文件名。这里的测试其实我写得不太好，应该直接系统默认读取工作目录就好了。建议你看一下getFileValue方法的具体实现，应该会对你的理解有帮助。另外为啥你会找到我做的项目而且还要跑一遍，这都是好久之前做的了而且很不完善 = =

思路非常有用，我学习了！
