### ISSUE TITLE
共同语言java

### ISSUE THREAD

**Issue by futongyao** [Jiangyuan-Chen/javaproject#8]
陈老师最新这版代码commitList()好像会输出别的分支的commit历史，这里是不是有点问题呀？

**Comment by Jiangyuan-Chen** [comment]
没有问题呀，如果一个分支是基于上一个分支新建的话，它会继承上一个分支的所有commit版本呢 :)

**Comment by futongyao** [comment]
好的陈老师！那咱们是不是还没有实现回滚后其他分支没有引用的之后的文件的删除呀？

**Comment by Jiangyuan-Chen** [comment]
阿豆这么严格的吗，我尽快push咯
